# Site settings
title: America Heroes Scholarship
description: > American Heroes Scholarship is a non-profit building the educational and economic future of high school and college students.
baseurl: "/creative-theme-jekyll-new/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2022 - American Heroes Scholarship
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
